/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Niilo Poutanen (https://sketchfab.com/niilo.poutanen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-tv-remote-38f2339bfc974f1e81fe7b1d2b96330a
Title: Apple TV remote
*/

"use client";
import { useGLTF } from "@react-three/drei";

type PropsType = {
  scale: any;
  item: any;
  size: any;
};

export default function Index({ scale, item, size }: PropsType) {
  const { nodes, materials }: any = useGLTF("/models/apple_tv_remote.glb");

  const props = {
    scale,
    item,
    size,
  };

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.0026]} scale={0.05}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[0.0043, 140.6112, 15.8004]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Frame_Frame_0.geometry}
              material={materials.Frame}
            />
            <mesh
              geometry={nodes.Frame_Black_plastic_0.geometry}
              material={materials.Black_plastic}
            />
            <mesh
              geometry={nodes.Frame_Metal_0.geometry}
              material={materials.Metal}
            />
            <mesh
              geometry={nodes.Frame_White_plastic_0.geometry}
              material={materials.White_plastic}
            />
            <mesh
              geometry={nodes.Frame_Gold_0.geometry}
              material={materials.Gold}
            />
            <mesh
              geometry={nodes.Frame_Frame_logo_0.geometry}
              material={materials.Frame_logo}
            />
            <mesh
              geometry={nodes.MainButton_Buttons_0.geometry}
              material={materials.Buttons}
              position={[0, 0.0201, 3.932]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Buttons_Buttons_0.geometry}
              material={materials.Buttons}
              position={[0.7534, -0.0198, 1.6556]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.VoiceButton_Frame_logo_0.geometry}
              material={materials.Frame_logo}
              position={[1.8184, 0.175, 3.9356]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              geometry={nodes.Power_button_Frame_logo_0.geometry}
              material={materials.Frame_logo}
              position={[0.7534, -0.0198, 1.6556]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.6174}
            />
            <mesh
              geometry={nodes.BoltRight_Metal_0.geometry}
              material={materials.Metal}
              position={[1.2956, 0.2277, -6.6743]}
              rotation={[Math.PI, 0.6008, -Math.PI]}
            />
            <mesh
              geometry={nodes.BoltLeft_Metal_0.geometry}
              material={materials.Metal}
              position={[-1.2924, 0.2277, -6.6756]}
              rotation={[Math.PI, -0.0032, Math.PI]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/apple_tv_remote.glb");
